export const SIDDUR_SECTIONS = [
  "Morning Blessings",
  "Akedah",
  "Sovereignty of Heaven",
  "Korbanot",
  "Pesukei Dezimra - Introductory Psalm",
  "Barukh She'amar",
  "Hodu",
  "Mizmor Letoda",
  "Yehi Chevod",
  "Ashrei",
  "Psalm 146",
  "Psalm 147",
  "Psalm 148",
  "Psalm 149",
  "Psalm 150",
  "Psalms - Closing Verses",
  "Vayevarech David",
  "Az Yashir",
  "Yishtabach",
  "Birchot Kriat Shema",
  "Amidah - Opening",
  "Amidah - Kedusha",
  "Amidah - Middle",
  "Amidah - Closing",
  "Tachanun",
  "Torah",
  "Ashrei - Conclusion",
  "Aleinu",
];
