import re

COMMENTARIES = [
    {
        "englishName": "Translation",
        "hebrewName": "Translation",
        "className": "translation",
    },
    {
        "englishName": "Verses",
        "category": "Tanakh",
        "hebrewName": 'תנ"ך',
        "className": "psukim",
        "showTitle": True,
    },
    {
        "englishName": "Mishnah",
        "category": "Mishnah",
        "hebrewName": "משנה",
        "className": "mishna",
        "showTitle": True,
    },
    {
        "englishName": "Tosefta",
        "englishNamePattern": re.compile("^Tosefta "),
        "hebrewName": "תוספתא",
        "className": "tosefta",
        "showTitle": True,
    },
    {
        "englishName": "Rashi",
        "hebrewName": 'רש"י',
        "className": "rashi",
    },
    {
        "englishName": "Otzar Laazei Rashi",
        "hebrewName": 'אוצר לעזי רש"י',
        "className": "otzar-laazei-rashi",
    },
    {
        "englishName": "Tosafot",
        "hebrewName": "תוספות",
        "className": "tosafot",
    },
    {
        "englishName": "Rabbeinu Chananel",
        "englishNamePattern": re.compile("^Rabbeinu Chananel on .*"),
        "hebrewName": 'ר"ח',
        "className": "rabbeinu-chananel",
    },
    {
        "englishName": "Ramban",
        "hebrewName": 'רמב"ן',
        "className": "ramban",
    },
    {
        "englishName": "Rashba",
        "hebrewName": 'רשב"א',
        "className": "rashba",
    },
    {
        "englishName": "Rashbam",
        "hebrewName": 'רשב"ם',
        "className": "rashbam",
    },
    {
        "englishName": "Maharsha",
        "englishNamePattern": re.compile("(Chidushei Halachot|Chidushei Agadot)"),
        "hebrewName": 'מהרש"א',
        "className": "maharsha",
    },
    {
        "englishName": "Maharshal",
        "englishNamePattern": re.compile("(Chokhmat Shlomo on .*|Chokhmat Shlomo)"),
        "hebrewName": 'מהרש"ל',
        "className": "maharshal",
    },
    {
        "englishName": "Meir Lublin",
        "englishNamePattern": re.compile("^Maharam$"),
        "hebrewName": 'מהר"ם לובלין',
        "className": "meir-lublin",
    },
    {
        "englishName": "Rosh",
        "englishNamePattern": re.compile("^Rosh on "),
        "hebrewName": 'רא"ש',
        "className": "rosh",
    },
    {
        "englishName": "Ritva",
        "hebrewName": 'ריטב"א',
        "className": "ritva",
    },
    {
        "englishName": "Rav Nissim Gaon",
        "englishNamePattern": re.compile("^Rav Nissim Gaon on "),
        "hebrewName": "רבנו נסים",
        "className": "rav-nissim-gaon",
    },
    {
        "englishName": "Shulchan Arukh",
        "englishNamePattern": re.compile("^Shulchan Arukh, "),
        "hebrewName": "שולחן ערוך",
        "className": "shulchan-arukh",
        "cssCategory": "ein-mishpat",
        "showTitle": True,
    },
    {
        "englishName": "Mishneh Torah",
        "englishNamePattern": re.compile("^Mishneh Torah, "),
        "hebrewName": "משנה תורה",
        "className": "mishneh-torah",
        "cssCategory": "ein-mishpat",
        "showTitle": True,
    },
    {
        "englishName": "Mesorat Hashas",
        "type": "mesorat hashas",
        "hebrewName": 'מסורת הש"ס',
        "className": "mesorat-hashas",
        "showTitle": True,
    },
    {
        "englishName": "Jastrow",
        "hebrewName": "Jastrow",
        "className": "jastrow",
    },
    {
        "englishName": "Abarbanel",
        "englishNamePattern": re.compile("^Abarbanel on"),
        "hebrewName": "אברבנאל",
        "className": "abarbanel",
    },
    {
        "englishName": "Guide for the Perplexed",
        "hebrewName": "מורה נבוכים",
        "className": "guide-perplexed",
    },
    {
        "englishName": "Haamek Davar",
        "englishNamePattern": re.compile("^Haamek Davar on"),
        "hebrewName": "העמק דבר",
        "className": "haamek-davar",
    },
    {
        "englishName": "Ibn Ezra",
        "englishNamePattern": re.compile("^Ibn Ezra on "),
        "hebrewName": "אבן עזרא",
        "className": "ibn-ezra",
    },
    {
        "englishName": "JPS 1985 Footnotes",
        "hebrewName": "JPS Footnotes",
        "className": "jps-1985",
    },
    {
        "englishName": "Kedushat Levi",
        "englishNamePattern": re.compile("^Kedushat Levi, "),
        "hebrewName": "קדושת לוי",
        "className": "kedushat-levi",
    },
    {
        "englishName": "Kli Yakar",
        "englishNamePattern": re.compile("^Kli Yakar on "),
        "hebrewName": "כלי יקר",
        "className": "kli-yakar",
    },
    {
        "englishName": "Malbim",
        "englishNamePattern": re.compile("^Malbim on "),
        "hebrewName": 'מלבי"ם',
        "className": "malbim",
    },
    {
        "englishName": "Mei HaShiloach",
        "hebrewName": "מי השלוח",
        "className": "mei-hashiloach",
    },
    {
        "englishName": "Meshech Hochma",
        "hebrewName": "משך חכמה",
        "className": "meshech-hochma",
    },
    {
        "englishName": "Radak",
        "englishNamePattern": re.compile("^Radak on "),
        "hebrewName": 'רד"ק',
        "className": "radak",
    },
    {
        "englishName": "Sefer HaChinukh",
        "hebrewName": "ספר החינוך",
        "className": "sefer-hachinukh",
    },
    {
        "englishName": "Sforno",
        "englishNamePattern": re.compile("^Sforno on "),
        "hebrewName": "ספורנו",
        "className": "sforno",
    },
    {
        "englishName": "Torah Temima",
        "englishNamePattern": re.compile("^Torah Temimah on "),
        "hebrewName": "תורה תמימה",
        "className": "torah-temima",
    },
    {
        "englishName": "Steinsaltz",
        "hebrewName": "שטיינזלץ",
        "className": "translation",
    },
]
