MASECHTOT = {
    "Arakhin": ("Arachin"),
    "Bava Kamma": ("Bava Kama"),
    "Bekhorot": ("Bechorot", "Bechoros"),
    "Chullin": ("Chulin"),
    "Gittin": ("Gitin"),
    "Keritot": ("Ceritot", "Kritot", "Critot"
                "Kerisos", "Cerisos", "Krisos", "Crisos"),
    "Makkot": ("Makot", "Macot", "Maccot",
               "Makos", "Macos", "Maccos", "Makkos"),
    "Menachot": ("Menakhot", "Menachos", "Menakhos"),
    "Nedarim": (),
    "Rosh Hashanah": ("Rosh Hashana"),
    "Shevuot": ("Shevuos"),
    "Taanit": ("Taanit", "Taanis", "Tanit", "Tanis"),
    "Yevamot": ("Yevamos"),
    "Avodah Zarah": ("Avoda Zarah", "Avoda Zara", "Avodah Zara"),
    "Bava Metzia": ("Bava Metziah", "Bava Metsia", "Bava Metsiah",
                    "Bava Metsiah", "Bava Metsia", "Bava Metsiah"),
    "Berakhot": ("Berachot", "Brachot", "Brakhot",
                 "Berachos", "Brachos", "Brakhos", "Berakhos"),
    "Ketubot": ("Kesubos",
                "Ktubot", "Ksubos"),
    "Megillah": ("Megilla", "Megila", "Megilah"),
    "Moed Katan": ("Moed Catan"),
    "Niddah": ("Nidda", "Nidah", "Nida"),
    "Sanhedrin": (),
    "Sotah": ("Sota"),
    "Tamid": (),
    "Yoma": ("Yuma", "Yomah", "Yumah"),
    "Bava Batra": ("Bava Basra"),
    "Beitzah": ("Beitza", "Beitsah", "Beitsa"),
    "Chagigah": ("Chagiga", "Khagigah", "Khagiga"),
    "Eruvin": (),
    "Horayot": ("Horayos"),
    "Kiddushin": ("Kidushin"),
    "Meilah": ("Meila"),
    "Nazir": (),
    "Pesachim": (),
    "Shabbat": ("Shabat", "Chabbat", "Chabat",
                "Shabos", "Chabbos", "Chabos",
                "Shabbas", "Shabbos"),
    "Sukkah": ("Sukka", "Suka", "Succah", "Succa"),
    "Temurah": ("Temura"),
    "Zevachim": ("Zvachim", "Zevakhim"),
}
