MASECHTOT = {
    "Arakhin": ("Arachin"),
    "Bava Kamma": ("Bava Kama"),
    "Bekhorot": ("Bechorot", "Bechoros"),
    "Chullin": ("Chulin"),
    "Gittin": ("Gitin"),
    "Keritot": ("Ceritot", "Kritot", "Critot"
                "Kerisos", "Cerisos", "Krisos", "Crisos"),
    "Makkot": ("Makot", "Macot", "Maccot",
               "Makos", "Macos", "Maccos", "Makkos"),
    "Menachot": ("Menakhot", "Menachos", "Menakhos"),
    "Nedarim": (),
    "Rosh Hashanah": ("Rosh Hashana"),
    "Shevuot": ("Shevuos"),
    "Taanit": ("Taanit", "Taanis", "Tanit", "Tanis"),
    "Yevamot": ("Yevamos"),
    "Avodah Zarah": ("Avoda Zarah", "Avoda Zara", "Avodah Zara"),
    "Bava Metzia": ("Bava Metziah", "Bava Metsia", "Bava Metsiah",
                    "Bava Metsiah", "Bava Metsia", "Bava Metsiah"),
    "Berakhot": ("Berachot", "Brachot", "Brakhot",
                 "Berachos", "Brachos", "Brakhos", "Berakhos"),
    "Ketubot": ("Kesubos",
                "Ktubot", "Ksubos"),
    "Megillah": ("Megilla", "Megila", "Megilah"),
    "Moed Katan": ("Moed Catan"),
    "Niddah": ("Nidda", "Nidah", "Nida"),
    "Sanhedrin": (),
    "Sotah": ("Sota"),
    "Tamid": (),
    "Yoma": ("Yuma", "Yomah", "Yumah"),
    "Bava Batra": ("Bava Basra"),
    "Beitzah": ("Beitza", "Beitsah", "Beitsa"),
    "Chagigah": ("Chagiga", "Khagigah", "Khagiga"),
    "Eruvin": (),
    "Horayot": ("Horayos"),
    "Kiddushin": ("Kidushin"),
    "Meilah": ("Meila"),
    "Nazir": (),
    "Pesachim": (),
    "Shabbat": ("Shabat", "Chabbat", "Chabat",
                "Shabos", "Chabbos", "Chabos",
                "Shabbas", "Shabbos"),
    "Sukkah": ("Sukka", "Suka", "Succah", "Succa"),
    "Temurah": ("Temura"),
    "Zevachim": ("Zvachim", "Zevakhim"),
}

LAST_AMUD_PER_MASECHET = {
  "Arakhin": "34a",
  "Avodah Zarah": "76b",
  "Bava Batra": "176b",
  "Bava Kamma": "119b",
  "Bava Metzia": "119a",
  "Beitzah": "40b",
  "Bekhorot": "61a",
  "Berakhot": "64a",
  "Chagigah": "27a",
  "Chullin": "142a",
  "Eruvin": "105a",
  "Gittin": "90b",
  "Horayot": "14a",
  "Keritot": "28b",
  "Ketubot": "112b",
  "Kiddushin": "82b",
  "Makkot": "24b",
  "Megillah": "32a",
  "Meilah": "22a",
  "Menachot": "110a",
  "Moed Katan": "29a",
  "Nazir": "66b",
  "Nedarim": "91b",
  "Niddah": "73a",
  "Pesachim": "121b",
  "Rosh Hashanah": "35a",
  "Sanhedrin": "113b",
  "Shabbat": "157b",
  "Shevuot": "49b",
  "Sotah": "49b",
  "Sukkah": "56b",
  "Taanit": "31a",
  "Tamid": "33b",
  "Temurah": "34a",
  "Yevamot": "122b",
  "Yoma": "88a",
  "Zevachim": "120b",
}
