MASECHTOT = {
    "Arakhin": ("Arachin"),
    "Bava Kamma": ("Bava Kama"),
    "Bekhorot": ("Bechorot"),
    "Chullin": ("Chulin"),
    "Gittin": ("Gitin"),
    "Keritot": ("Ceritot"),
    "Makkot": ("Makot", "Macot", "Maccot"),
    "Menachot": ("Menakhot"),
    "Nedarim": (),
    "Rosh Hashanah": ("Rosh Hashana"),
    "Shevuot": (),
    "Taanit": ("Taanit"),
    "Yevamot": (),
    "Avodah Zarah": ("Avoda Zarah", "Avoda Zara", "Avodah Zara"),
    "Bava Metzia": ("Bava Metziah", "Bava Metsia", "Bava Metsiah"),
    "Berakhot": ("Berachot", "Brachot", "Brakhot"),
    "Ketubot": (),
    "Megillah": ("Megilla", "Megila", "Megilah"),
    "Moed Katan": ("Moed Catan"),
    "Niddah": ("Nidda", "Nidah", "Nida"),
    "Sanhedrin": (),
    "Sotah": ("Sota"),
    "Tamid": (),
    "Yoma": ("Yuma", "Yomah", "Yumah"),
    "Bava Batra": (),
    "Beitzah": ("Beitza", "Beitsah"),
    "Chagigah": ("Chagiga", "Khagigah", "Khagiga"),
    "Eruvin": (),
    "Horayot": (),
    "Kiddushin": ("Kidushin"),
    "Meilah": ("Meila"),
    "Nazir": (),
    "Pesachim": (),
    "Shabbat": ("Shabat", "Chabbat", "Chabat"),
    "Sukkah": ("Sukka", "Suka", "Succah", "Succa"),
    "Temurah": ("Temura"),
    "Zevachim": (),
}
