/* eslint-disable no-console */
// Sequential requests on purpose: this is a one-off script and Sefaria rate-limits.
/* eslint-disable no-await-in-loop */
// Generates print/model/korenSiddurToc.ts from Sefaria's index of "The Koren Shalem Siddur;
// Ashkenaz". The output is committed so the client and offline rendering don't depend on it.
//
//   npx ts-node print/cli/generate_koren_toc.ts

import * as fs from "fs";
import * as path from "path";
import {fetch} from "../../fetch";

const INDEX = "The Koren Shalem Siddur; Ashkenaz";
const OUT = path.join(__dirname, "..", "model", "korenSiddurToc.ts");

interface Node {
  titles?: {lang: string; text: string; primary?: boolean}[];
  sharedTitle?: string;
  nodes?: Node[];
}

const termCache = new Map<string, [string, string]>();

async function getJson(url: string): Promise<any> {
  return (await fetch(url, {retry: {retries: 4, minTimeout: 200}})).json();
}

async function names(node: Node): Promise<[string, string]> {
  let titles = node.titles ?? [];
  if (titles.length === 0 && node.sharedTitle) {
    if (!termCache.has(node.sharedTitle)) {
      const term = await getJson(`https://www.sefaria.org/api/terms/${encodeURIComponent(node.sharedTitle)}`);
      titles = term.titles ?? [];
      const en = titles.find((x: any) => x.lang === "en" && x.primary)?.text ?? node.sharedTitle;
      const he = titles.find((x: any) => x.lang === "he" && x.primary)?.text ?? "";
      termCache.set(node.sharedTitle, [en, he]);
    }
    return termCache.get(node.sharedTitle)!;
  }
  const en = titles.find(x => x.lang === "en" && x.primary)?.text ?? node.sharedTitle ?? "";
  const he = titles.find(x => x.lang === "he" && x.primary)?.text ?? "";
  return [en, he];
}

(async () => {
  const index = await getJson(`https://www.sefaria.org/api/v2/raw/index/${encodeURIComponent(INDEX)}`);
  const entries: string[] = [];
  for (const group of index.schema.nodes as Node[]) {
    const [groupEn, groupHe] = await names(group);
    const leaves = group.nodes ?? [group];
    for (const leaf of leaves) {
      const [en, he] = leaf === group ? [groupEn, groupHe] : await names(leaf);
      const pathSuffix = leaf === group ? en : `${groupEn}, ${en}`;
      entries.push(`  [${JSON.stringify(group.nodes ? groupEn : "Introduction")}, `
        + `${JSON.stringify(group.nodes ? groupHe : "הקדמות")}, ${JSON.stringify(pathSuffix)}, `
        + `${JSON.stringify(en)}, ${JSON.stringify(he)}],`);
    }
  }
  const header = [
    "// Generated by print/cli/generate_koren_toc.ts from Sefaria's index of",
    `// "${INDEX}". Do not edit by hand.`,
    "",
    "// [group, groupHebrew, path (after the book title), title, titleHebrew]",
    "export const KOREN_SIDDUR_TOC: [string, string, string, string, string][] = [",
  ];
  fs.writeFileSync(OUT, [...header, ...entries, "];", ""].join("\n"));
  console.log(`Wrote ${entries.length} sections to ${OUT}`);
})();
