/* eslint-disable no-console */
// Sequential requests on purpose: a one-off script.
/* eslint-disable no-await-in-loop */
// Generates print/model/parshiyot.ts: the weekly Torah portions with their aliyot, including the
// aliyot used when two portions are read together.
//
// Aliyot come from @hebcal/leyning (BSD-2-Clause, https://github.com/hebcal/hebcal-leyning);
// Hebrew names from Sefaria's index terms.
//
//   npm pack @hebcal/leyning && tar xzf hebcal-leyning-*.tgz   (in a temp dir)
//   npx ts-node print/cli/generate_parshiyot.ts /path/to/package/dist/esm/aliyot.json.js

import * as fs from "fs";
import * as path from "path";
import {fetch} from "../../fetch";

const OUT = path.join(__dirname, "..", "model", "parshiyot.ts");
const BOOKS = ["Genesis", "Exodus", "Leviticus", "Numbers", "Deuteronomy"];

async function getJson(url: string): Promise<any> {
  return (await fetch(url, {retry: {retries: 4, minTimeout: 200}})).json();
}

(async () => {
  const aliyotFile = process.argv[2];
  if (!aliyotFile) throw new Error("Pass the path to @hebcal/leyning's dist/esm/aliyot.json.js");
  // The module is `export default {...};` possibly followed by a source map comment.
  const source = fs.readFileSync(aliyotFile, "utf8");
  const json = source.slice(source.indexOf("{"), source.lastIndexOf("}") + 1);
  const hebcal: Record<string, any> = JSON.parse(json);

  // Sefaria's parasha names (in order) give the Hebrew names.
  const sefaria: {name: string; hebrewName: string}[] = [];
  for (const book of BOOKS) {
    const index = await getJson(`https://www.sefaria.org/api/v2/raw/index/${book}`);
    for (const node of index.alt_structs.Parasha.nodes) {
      const term = await getJson(`https://www.sefaria.org/api/terms/${encodeURIComponent(node.sharedTitle)}`);
      const hebrewName = term.titles?.find((x: any) => x.lang === "he" && x.primary)?.text ?? "";
      sefaria.push({name: node.sharedTitle, hebrewName});
    }
  }

  const entries: string[] = [];
  for (const [id, value] of Object.entries(hebcal)) {
    const numbers: number[] = Array.isArray(value.num) ? value.num : [value.num];
    const names = numbers.map(n => sefaria[n - 1]);
    const aliyot = Object.entries<string[]>(value.fullkriyah)
      .map(([label, [start, end]]) => ({label, start, end}));
    const main = aliyot.filter(x => x.label !== "M");
    entries.push(`  ${JSON.stringify({
      id,
      name: names.map(x => x.name).join("-"),
      hebrewName: names.map(x => x.hebrewName).join("-"),
      book: BOOKS[value.book - 1],
      start: main[0].start,
      end: main[main.length - 1].end,
      combined: Boolean(value.combined),
      parts: value.combined ? [value.p1, value.p2] : undefined,
      aliyot,
    })},`);
  }

  fs.writeFileSync(OUT, [
    "// Generated by print/cli/generate_parshiyot.ts. Do not edit by hand.",
    "// Aliyot from @hebcal/leyning (BSD-2-Clause, https://github.com/hebcal/hebcal-leyning).",
    "// Hebrew names from Sefaria.",
    "/* eslint-disable max-len */",
    "",
    "export interface AliyahRange {",
    "  // \"1\"..\"7\", or \"M\" for maftir.",
    "  label: string;",
    "  start: string; // chapter:verse",
    "  end: string;",
    "}",
    "",
    "export interface ParshaInfo {",
    "  id: string;",
    "  name: string;",
    "  hebrewName: string;",
    "  book: string;",
    "  start: string;",
    "  end: string;",
    "  // A double portion, read together in some years.",
    "  combined: boolean;",
    "  parts?: string[];",
    "  aliyot: AliyahRange[];",
    "}",
    "",
    "export const PARSHIYOT: ParshaInfo[] = [",
    ...entries,
    "];",
    "",
  ].join("\n"));
  console.log(`Wrote ${entries.length} parshiyot to ${OUT}`);
})();
