name: Deploy to GCP
run-name: "[Deploy] ${{ github.event.workflow_run.head_commit.message }}"

on:
  workflow_run:
    branches: [base]
    workflows: ["Tests"]
    types: [completed]

jobs:
  gcp_deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - run: 'npm install --no-audit'

    - id: configure-email
      env:
        MAILJET_API_KEY: ${{ secrets.MAILJET_API_KEY }}
        MAILJET_API_SECRET: ${{ secrets.MAILJET_API_SECRET }}
        IGNORE_EMAIL_ADDRESSES: ${{ secrets.IGNORE_EMAIL_ADDRESSES }}
      run: |
        echo -n ${MAILJET_API_KEY} > mailjet_api_key
        echo -n ${MAILJET_API_SECRET} > mailjet_api_secret
        echo -n ${IGNORE_EMAIL_ADDRESSES} > ignore_email_addresses

    - id: 'build'
      run: 'npm run parcel-prod'

    - id: 'auth'
      # Note: make sure that the roles are configured in the IAM tab and not under the
      # Service Accounts > Permissions page. This is confusing!
      uses: 'google-github-actions/auth@v2'
      env:
        GCP_DEPLOY_SERVICE_ACCOUNT: ${{ secrets.GCP_DEPLOY_SERVICE_ACCOUNT }}
      with:
        project_id: 'talmud'
        credentials_json: '${{ secrets.GCP_DEPLOY_SERVICE_ACCOUNT }}'

    - id: 'verify-gcloud'
      run: 'gcloud --version'

    - id: 'verify-auth'
      run: 'gcloud auth list'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v2'
